### ISSUE TITLE
DeploymentMode: Validate fails with exit code 2

### ISSUE THREAD

**Issue by kanika1894** [whiteducksoftware/azure-arm-action-js#13]
![image](https://user-images.githubusercontent.com/58769601/91280448-639b5b00-e7a4-11ea-8e15-cfa5ffcc13e2.png)

It worked fine with the deploymentMode as incremental

**Comment by nmeisenzahl** [comment]
@StiviiK fyi

**Comment by StiviiK** [comment]
The deployment mode parameter is the deployment mode parameter which gets directly passed to CLI, so the only allowed values are `Incremental` and `Complate`.

**Comment by StiviiK** [comment]
But I have added a new parameter `validationOnly`.
