### ISSUE TITLE
Scope: management group is failing

### ISSUE THREAD

**Issue by kanika1894** [whiteducksoftware/azure-arm-action-js#15]
![image](https://user-images.githubusercontent.com/58769601/91331890-07a6f580-e7e9-11ea-9488-eecfadce4d06.png)

The same template works fine when I am using Azure CLI.
I tried both, providing the url as well as the putting the tempplate in examples folder.

**Comment by StiviiK** [comment]
With a local file you need to pass the path as a full-path or as a relative path. In your example it would be `./examples/temaplte/parameters.json`. I have to admit its wrong and not clear in the example.
The URL issue I will look into.
The whole issue seems to be related to #12.

**Comment by kanika1894** [comment]
I don't think so the file path is the issue. 
As the following worked fine :

![image](https://user-images.githubusercontent.com/58769601/91336757-07f6bf00-e7f0-11ea-829d-5f3640ea4a5c.png)

**Comment by StiviiK** [comment]
The Issue was that the `managementGroupId` is missing. I will add a new Input.
