### ISSUE TITLE
How do I pass the template parameters file? 

### ISSUE THREAD

**Issue by samsmithnz** [whiteducksoftware/azure-arm-action-js#7]
## Describe the bug
If looks like we have a clear description for override parameters, but not the parameters file. Is this planned?

**Comment by nmeisenzahl** [comment]
Hey @samsmithnz you have taken a short look at our containerized version (https://github.com/whiteducksoftware/azure-arm-action)? This one allows providing a parameter file. 

We are planning to get the js based version into feature parity soon.
This is an open-source project. Any help is appreciated.

Greets Nico

fyi @mjisaak

**Comment by nmeisenzahl** [comment]
Hi @samsmithnz, I just verified and tested it. We are using the Azure CLI (az) under the hood. The specified parameter values get mapped to `az group deployment create --parameters`. With this we support everything the CLI does. Values, local or remote value files as well as a combination of both.
I will update the documentation.
